export {AnimationPage} from './AnimationPage';
export {BindingGuidePage} from './BindingGuidePage';
export {DancePage} from './DancePage';
export {MotionPage} from './MotionPage';
export {NotificationPage} from './NotificationPage';
export {ScanCodePage} from './ScanCodePage';
export {SurveillancePage} from './SurveillancePage';
export {VisitSessionPage} from './VisitSessionPage';
export {WifiSelectPage} from './WifiSelectPage';
